### ISSUE TITLE
Bugs in reproducing the code

### ISSUE THREAD

**Issue by raneeny** [liuxz1011/TodyNet#6]
Dear Author, 

We are trying to reproduce your code in one of the data you shared (atrial fibrillation), and we have different errors. Can you please provide us with instructions on the requirements we should have to run your project,
one of the bugs we have, for example as follows:
    x, adj = pool( gconv( tconv(x), adj ), adj )

  File ~\AppData\Roaming\Python\Python311\site-packages\torch\nn\modules\module.py:1501 in _call_impl
    return forward_call(*args, **kwargs)

  File ~\AppData\Roaming\Python\Python311\site-packages\torch\nn\modules\conv.py:463 in forward
    return self._conv_forward(input, self.weight, self.bias)

  File ~\AppData\Roaming\Python\Python311\site-packages\torch\nn\modules\conv.py:459 in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,

RuntimeError: Given groups=1, weight of size [64, 1, 1, 9], expected input[1, 16, 206, 4] to have 1 channels, but got 16 channels instead

**Comment by liuxz1011** [comment]
Sorry for slow response. According to "input[1, 16, 206, 4]", it looks like you are getting this error when running the 'Epilepsy' dataset. I presume this is due to you using the wrong dataset if you haven't changed anything in the source code

**Comment by liuxz1011** [comment]
Sorry for slow response.
According to "input[1, 16, 206, 4]", it looks like you are getting this error when running the 'Epilepsy' dataset. I speculate that this is due to you using the wrong dataset (if you haven't modified the content in the source code).
The dataset is sourced from [this website](http://www.timeseriesclassification.com/), but we had modified the dimensions and format of the dataset. The modified format is shown in the provided 'data' file(NATOPS&AF).
You can modify the original dataset on the website based on the format provided in the 'data' file. Alternatively, I can also directly provide the processed data on GitHub.

**Comment by raneeny** [comment]
Thanks for your response!
We downloaded the repository and tried to run it on the datasets already given in the data folder, and we did not change anything in the code

**Comment by liuxz1011** [comment]
I just tried running the program using command

>python train.py --dataset=AtrialFibrillation

and it worked fine. Perhaps you can try re-downloading the project and run it following the command above? If you still encounter any errors, please let me know the error message. Thank you. 
(Also, I apologize that my next response may be after 10 hours.)

**Comment by raneeny** [comment]
Thank you now it worked

**Comment by liuxz1011** [comment]
You're welcome.
